import "./globals.css";

/** Top most or the root layout. If you delete this file it will get auto generated by next.
 * This children prop will render the topmost page.tsx or page.js.
 * Children should added as a prop !!!imp
 */
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: "lightblue",
            padding: "1rem",
          }}
        >
          <p>HEADER</p>
        </header>
        {children}
        <footer
          style={{
            backgroundColor: "lightblue",
            padding: "1rem",
          }}
        >
          <p>FOOTER</p>
        </footer>
      </body>
    </html>
  );
}
